// products.ts
export const productList = [
  {
    id: "DIYFT01",
    title: "Clay Diva Set",
    description: "Enhance your festive decor with this exquisite set of 2 Divine Foot Diya Pairs.",
    price: 99,
    originalPrice: 199,
    image: "/product1.jpg",
    image2: "/product1-2.jpg", // placeholder
    image3: "/product1-3.jpg", // placeholder
  },
  {
    id: "DIYFT02",
    title: "Handcrafted Diya",
    description: " This beautifully handcrafted red diya features an intricately designed hand-shaped base adorned with gold and green accents",
    price: 99,
    originalPrice: 199,
    image: "/product2.jpg",
    image2: "/product2-2.jpg",
    image3: "/product2-2.jpg",
  },
  {
    id: "DIYFT03",
    title: "Colourfull Diya",
    description: ".Illuminate your home with this vibrant Handcrafted Terracotta Diya, perfect for Diwali and daily rituals.",
    price: 79,
    originalPrice: 149,
    image: "/product3.jpg",
    image2: "/product3-2.jpg",
    image3: "/product3-3.jpg",
  },
   {
    id: "DIYFT04",
    title: "Festive Toran",
    description: "Handcrafted metal diya features intricate petal designs adorned with colored stones. Perfect for adding a warm, traditional glow to your festive décor.",
    price: 99,
    originalPrice: 129,
    image: "/product4.jpg",
    image2: "/product4-2.jpg",
    image3: "/product4-3.jpg",
  },
 /*  {
    id: "DIYFT05",
    title: "Rangoli Set",
    description: "Bright colored rangoli powder set for creative designs.",
    price: 89,
    originalPrice: 159,
    image: "/product5.jpg",
    image2: "/product5-2.jpg",
    image3: "/product5-3.jpg",
  },
  {
    id: "DIYFT06",
    title: "Decorative Plate",
    description: "Hand-painted plate for gifting or home decoration.",
    price: 159,
    originalPrice: 259,
    image: "/product6.jpg",
    image2: "/product6-2.jpg",
    image3: "/product6-3.jpg",
  },
  {
    id: "DIYFT07",
    title: "Mini Diyas Set",
    description: "Pack of 6 colorful mini diyas for festive lighting.",
    price: 79,
    originalPrice: 149,
    image: "/product7.jpg",
    image2: "/product7-2.jpg",
    image3: "/product7-3.jpg",
  },
  {
    id: "DIYFT08",
    title: "Handmade Candle Holder",
    description: "Wooden candle holder with intricate carvings.",
    price: 199,
    originalPrice: 299,
    image: "/product8.jpg",
    image2: "/product8-2.jpg",
    image3: "/product8-3.jpg",
  },
  {
    id: "DIYFT09",
    title: "Decorative Vase",
    description: "Elegant ceramic vase for floral arrangements.",
    price: 249,
    originalPrice: 349,
    image: "/product9.jpg",
    image2: "/product9-2.jpg",
    image3: "/product9-3.jpg",
  },
  {
    id: "DIYFT10",
    title: "Festive Wall Hanging",
    description: "Handmade wall hanging with traditional motifs.",
    price: 179,
    originalPrice: 279,
    image: "/product10.jpg",
    image2: "/product10-2.jpg",
    image3: "/product10-3.jpg",
  },
  {
    id: "DIYFT11",
    title: "Decorative Lamp",
    description: "Stylish lamp for living room or bedroom.",
    price: 399,
    originalPrice: 499,
    image: "/product11.jpg",
    image2: "/product11-2.jpg",
    image3: "/product11-3.jpg",
  },
  {
    id: "DIYFT12",
    title: "Pooja Thali Set",
    description: "Complete thali set for pooja rituals and ceremonies.",
    price: 349,
    originalPrice: 449,
    image: "/product12.jpg",
    image2: "/product12-2.jpg",
    image3: "/product12-3.jpg",
  },
  {
    id: "DIYFT13",
    title: "Decorative Coasters",
    description: "Set of 6 handmade coasters for tables.",
    price: 99,
    originalPrice: 159,
    image: "/product13.jpg",
    image2: "/product13-2.jpg",
    image3: "/product13-3.jpg",
  },
  {
    id: "DIYFT14",
    title: "Handmade Cushion Cover",
    description: "Colorful cushion cover for sofa or bed.",
    price: 149,
    originalPrice: 229,
    image: "/product14.jpg",
    image2: "/product14-2.jpg",
    image3: "/product14-3.jpg",
  },
  {
    id: "DIYFT15",
    title: "Decorative Garland",
    description: "Festive garland to enhance home decoration.",
    price: 129,
    originalPrice: 209,
    image: "/product15.jpg",
    image2: "/product15-2.jpg",
    image3: "/product15-3.jpg",
  },
  {
    id: "DIYFT16",
    title: "Handmade Diya Stand",
    description: "Decorative stand for multiple diyas.",
    price: 199,
    originalPrice: 299,
    image: "/product16.jpg",
    image2: "/product16-2.jpg",
    image3: "/product16-3.jpg",
  },
  {
    id: "DIYFT17",
    title: "Decorative Candle Set",
    description: "Set of 3 scented candles for home.",
    price: 179,
    originalPrice: 259,
    image: "/product17.jpg",
    image2: "/product17-2.jpg",
    image3: "/product17-3.jpg",
  },
  {
    id: "DIYFT18",
    title: "Handcrafted Table Lamp",
    description: "Unique table lamp with artistic design.",
    price: 399,
    originalPrice: 499,
    image: "/product18.jpg",
    image2: "/product18-2.jpg",
    image3: "/product18-3.jpg",
  },
  {
    id: "DIYFT19",
    title: "Festive Candle Holder",
    description: "Elegant candle holder for celebrations.",
    price: 159,
    originalPrice: 259,
    image: "/product19.jpg",
    image2: "/product19-2.jpg",
    image3: "/product19-3.jpg",
  },
  {
    id: "DIYFT20",
    title: "Decorative Bowl Set",
    description: "Set of 3 bowls for festive occasions.",
    price: 199,
    originalPrice: 299,
    image: "/product20.jpg",
    image2: "/product20-2.jpg",
    image3: "/product20-3.jpg",
  },
  */
]; 